### ISSUE TITLE
argument --version NameError: global name 'versions' is not defined

### ISSUE THREAD

**Issue by dkozovsk** [staticafi/symbiotic#113]
When I used argument --version the outpud looked like (tried on Fedora 28):

```
version: 6.1.0-dev
LLVM version: 4.0.1
Traceback (most recent call last):
  File "./symbiotic", line 219, in <module>
    tool, sources, opts, environment = setup_symbiotic()
  File "./symbiotic", line 170, in setup_symbiotic
    opts, args = parse_command_line(environment)
  File "/.../symbiotic/install/lib/symbioticpy/symbiotic/options.py", line 201, in parse_command_line
    print_versions()
  File "/.../symbiotic/install/lib/symbioticpy/symbiotic/options.py", line 119, in print_versions
    for (k, v) in versions.items():
NameError: global name 'versions' is not defined
```

**Comment by mchalupa** [comment]
A fix should be in master now. Can you check? Thanks.

**Comment by dkozovsk** [comment]
Ok, now the error is no longer present, thanks.
