### ISSUE TITLE
KLEE crash with LLVM 8 in `klee::Executor::getKValueInfo(klee::ExecutionState&, klee::KValue const&) const`

### ISSUE THREAD

**Issue by lzaoral** [staticafi/symbiotic#198]
System: Ubuntu 18.04 (ubuntu:bionic container)
LLVM & Clang: 8
Build type: RelWithDebInfo (Debug is does not crash though)
Compiler: `clang-8`

This crash can be seen in many test cases in the new CI draft, for instance in `simple_true-valid-memsafety_false-valid-memcleanup.c`.

Output with ASAN & UBSAN enabled:
```console
$ symbiotic --prp=memcleanup tests/simple_true-valid-memsafety_false-valid-memcleanup.c
8.0.0-pre-llvm-8.0.0-symbiotic:94e53f0e-dg:06c8ca8c-sbt-slicer:b0864a5b-sbt-instrumentation:c34d55f2-klee:10e5fae9
INFO: Looking for unfreed memory
INFO: Starting instrumentation
INFO: Instrumentation time: 0.08374357223510742
INFO: Optimizations time: 0.02287125587463379
Linked our definitions to these undefined functions:
  __VERIFIER_exit
INFO: Starting slicing
INFO: Total slicing time: 0.021975278854370117
INFO: Optimizations time: 0.012139558792114258
INFO: After-slicing optimizations and transformations time: 1.0967254638671875e-05
INFO: Starting verification
/symbiotic/klee/lib/Core/Executor.cpp:2977:28: runtime error: downcast of address 0x604000018bd0 which does not point to an object of type 'klee::KGEPInstruction'
KLEE: WARNING ONCE: Alignment of memory from call "malloc" is not modelled. Using alignment of 8.
/symbiotic/klee/lib/Core/Memory.h:167:25: runtime error: index 18 out of bounds for type 'const char [10]'
==27187==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000000d15192 at pc 0x0000005ea60f bp 0x7ffccc75f230 sp 0x7ffccc75e9d8
KLEE: output directory is "/tmp/symbiotic-odl2y93e/klee-out-0"
KLEE: Using Z3 solver backend
/symbiotic/klee/lib/Core/Executor.cpp:2977:28: runtime error: downcast of address 0x604000018bd0 which does not point to an object of type 'klee::KGEPInstruction'
0x604000018bd0: note: object is of type 'klee::KInstruction'
 0b 00 00 53  d0 cb e6 00 00 00 00 00  38 30 00 00 80 60 00 00  d0 71 01 00 30 60 00 00  b0 6e 02 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'klee::KInstruction'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /symbiotic/klee/lib/Core/Executor.cpp:2977:28 in 
KLEE: WARNING ONCE: Alignment of memory from call "malloc" is not modelled. Using alignment of 8.
/symbiotic/klee/lib/Core/Memory.h:167:25: runtime error: index 18 out of bounds for type 'const char [10]'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /symbiotic/klee/lib/Core/Memory.h:167:25 in 
=================================================================
==27187==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000000d15192 at pc 0x0000005ea60f bp 0x7ffccc75f230 sp 0x7ffccc75e9d8
READ of size 1 at 0x000000d15192 thread T0
    #0 0x5ea60e in strlen (/symbiotic/install/llvm-8.0.0/bin/klee+0x5ea60e)
    #1 0x7ff1f5202406 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x127406)
    #2 0x7b54f1 in klee::MemoryObject::getSegmentString[abi:cxx11]() const /symbiotic/klee/lib/Core/Memory.h:167:12
    #3 0x768d75 in klee::Executor::getKValueInfo[abi:cxx11](klee::ExecutionState&, klee::KValue const&) const /symbiotic/klee/lib/Core/Executor.cpp:3187:33
    #4 0x75cb86 in klee::Executor::terminateStateOnExit(klee::ExecutionState&) /symbiotic/klee/lib/Core/Executor.cpp:3430:15
    #5 0x8c841e in klee::SpecialFunctionHandler::handle(klee::ExecutionState&, llvm::Function*, klee::KInstruction*, std::vector<klee::Cell, std::allocator<klee::Cell> > const&) /symbiotic/klee/lib/Core/SpecialFunctionHandler.cpp:257:7
    #6 0x739583 in klee::Executor::callExternalFunction(klee::ExecutionState&, klee::KInstruction*, llvm::Function*, std::vector<klee::Cell, std::allocator<klee::Cell> > const&) /symbiotic/klee/lib/Core/Executor.cpp:3691:31
    #7 0x736652 in klee::Executor::executeCall(klee::ExecutionState&, klee::KInstruction*, llvm::Function*, std::vector<klee::Cell, std::allocator<klee::Cell> > const&) /symbiotic/klee/lib/Core/Executor.cpp:1507:7
    #8 0x754bb8 in klee::Executor::executeInstruction(klee::ExecutionState&, klee::KInstruction*) /symbiotic/klee/lib/Core/Executor.cpp:2145:7
    #9 0x763c15 in klee::Executor::run(klee::ExecutionState&) /symbiotic/klee/lib/Core/Executor.cpp:3139:5
    #10 0x77bb34 in klee::Executor::runFunctionAsMain(llvm::Function*, int, char**, char**) /symbiotic/klee/lib/Core/Executor.cpp:4498:3
    #11 0x6cd1df in main /symbiotic/klee/tools/klee/main.cpp:1808:18
    #12 0x7ff1f412abf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #13 0x5d6fc9 in _start (/symbiotic/install/llvm-8.0.0/bin/klee+0x5d6fc9)

0x000000d15192 is located 46 bytes to the left of global variable '<string literal>' defined in '/symbiotic/klee/lib/Core/Memory.h:173:14' (0xd151c0) of size 9
  '<string literal>' is ascii string 'symbolic'
0x000000d15192 is located 8 bytes to the right of global variable '<string literal>' defined in '/symbiotic/klee/lib/Core/Memory.h:167:25' (0xd15180) of size 10
  '<string literal>' is ascii string 'Segment: '
SUMMARY: AddressSanitizer: global-buffer-overflow (/symbiotic/install/llvm-8.0.0/bin/klee+0x5ea60e) in strlen
Shadow bytes around the buggy address:
  0x00008019a9e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008019a9f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008019aa00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008019aa10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008019aa20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x00008019aa30: 00 02[f9]f9 f9 f9 f9 f9 00 01 f9 f9 f9 f9 f9 f9
  0x00008019aa40: 04 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x00008019aa50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008019aa60: 00 02 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x00008019aa70: 00 00 00 00 00 00 00 00 00 00 00 07 f9 f9 f9 f9
  0x00008019aa80: 00 00 00 00 00 02 f9 f9 f9 f9 f9 f9 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==27187==ABORTING
klee answered ERROR (KLEE exited with 1)
INFO: Verification time: 0.15619134902954102
Failure!
NOTE: In the future, the result is going to be reported in SV-COMP format only with --report=sv-comp switch
RESULT: ERROR (KLEE exited with 1)
INFO: Total time elapsed: 0.6952133178710938
```

Blocks: #196 

edit: add more precise system information

**Comment by mchalupa** [comment]
> Note, that this issue might be present in upstream KLEE as well.

Nope, upstream KLEE does not use segments in pointer representation. This was solely our bug.
