### ISSUE TITLE
Symbiotic crashes on a simple code

### ISSUE THREAD

**Issue by vlstill** [staticafi/symbiotic#71]
```
$ ./install/bin/symbiotic --cflags='-I/usr/local/include -I/usr/bin/../lib/clang/4.0.1/include' --prp=memsafety mem_heap_bug01.c
After compilation stats: Globals/Functions/Blocks/Instr.: 0 1 4 18
Before instrumentation stats: Globals/Functions/Blocks/Instr.: 17 23 103 632
After instrumentation stats: Globals/Functions/Blocks/Instr.: 17 23 103 674
INFO: Compilation, preparation and instrumentation time: 0.21235370635986328
Statistics before Globals/Functions/Blocks/Instr.: 17 19 185 763
Statistics after Globals/Functions/Blocks/Instr.: 17 7 79 345
INFO: Total slicing time: 0.11650943756103516
Linked our definitions to these undefined functions:
  __VERIFIER_malloc0
INFO: After-slicing optimizations and preparation time: 0.04294872283935547
INFO: Starting verification
Before verification stats: Globals/Functions/Blocks/Instr.: 18 8 78 357
klee: /home/xstill/repo/symbiotic/klee/include/klee/Expr.h:1085: static klee::ref<klee::ConstantExpr> klee::ConstantExpr::create(uint64_t, klee::Expr::Width): Assertion `v == bits64::truncateToNBits(v, w) && "invalid constant"' failed.
KLEE: output directory is "/tmp/symbiotic-xw54pljy/klee-out-0"
KLEE: Using STP solver backend
klee: /home/xstill/repo/symbiotic/klee/include/klee/Expr.h:1085: static klee::ref<klee::ConstantExpr> klee::ConstantExpr::create(uint64_t, klee::Expr::Width): Assertion `v == bits64::truncateToNBits(v, w) && "invalid constant"' failed.
0  klee            0x000000c0838ba388 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 56
1  klee            0x000000c0838b7e56 llvm::sys::RunSignalHandlers() + 54
2  klee            0x000000c0838b8060
3  libpthread.so.0 0x00007fab676637e0
4  libc.so.6       0x00007fab66a2e8c0 gsignal + 272
5  libc.so.6       0x00007fab66a2ff72 abort + 434
6  libc.so.6       0x00007fab66a275be
7  libc.so.6       0x00007fab66a27633
8  klee            0x000000c082c11bc0 klee::Expr::createPointer(unsigned long) + 416
9  klee            0x000000c082bcb2c3 klee::Executor::initializeGlobals(klee::ExecutionState&) + 179
10 klee            0x000000c082bda935 klee::Executor::runFunctionAsMain(llvm::Function*, int, char**, char**) + 1701
11 klee            0x000000c082b9a08b main + 9435
12 libc.so.6       0x00007fab66a1b4ca __libc_start_main + 234
13 klee            0x000000c082bb943a _start + 42
Traceback (most recent call last):
  File "/home/xstill/repo/symbiotic/install/lib/symbioticpy/symbiotic/symbiotic.py", line 487, in run_verification
    self._run(cmd, watch, 'Running the verifier failed')
  File "/home/xstill/repo/symbiotic/install/lib/symbioticpy/symbiotic/symbiotic.py", line 173, in _run
    raise SymbioticException(err_msg)
symbiotic.exceptions.SymbioticException: Running the verifier failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./install/bin/symbiotic", line 611, in <module>
    res = symbiotic.run()
  File "/home/xstill/repo/symbiotic/install/lib/symbioticpy/symbiotic/symbiotic.py", line 516, in run
    return self._run_symbiotic();
  File "/home/xstill/repo/symbiotic/install/lib/symbioticpy/symbiotic/symbiotic.py", line 712, in _run_symbiotic
    found = self.run_verification()
  File "/home/xstill/repo/symbiotic/install/lib/symbioticpy/symbiotic/symbiotic.py", line 489, in run_verification
    print_stderr(e.message, color='RED')
AttributeError: 'SymbioticException' object has no attribute 'message'
```

the code:

```{.c}
#include <stdlib.h>

int main() {
    int *array = malloc( 32 );
    if ( array == 0 ) {
        return 1;
    }
    array[ 4 ] = 16;
}
```

**Comment by mchalupa** [comment]
The problem with python exception was fixed in the last commit. The rest is a bug in KLEE where KLEE truncates pointer to memory allocated on 64-bit system to 32-bit pointer because the bitcode is 32-bit.

**Comment by mchalupa** [comment]
Should now work fine on 64-bit systems as 64-bit mode was set as default. May still be a problem when --32 option is used. As this is a bug in KLEE, I'm closing this issue here.
